/**
 * Copyright (c) 2014-2016 by the respective copyright holders.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 */
package org.openhab.binding.dlinksmartplugs.internal;

/**
 * The {@link VARS_HNAP_AUTH} is nothing more than a place to save variable values to in memory.
 * it is used by the SoapClient.
 *
 * @author Jereme Guenther - Initial contribution
 */
public class VARS_HNAP_AUTH {
    /**
     * URL to the plug.
     */
    public String URL = "";
    /**
     * Username to log into the plug.
     */
    public String User = "";
    /**
     * Password to log into the plug.
     */
    public String Pwd = "";
    /**
     * soap result to the plug.
     */
    public String Result = "";
    /**
     * challenge value to help build private key.
     */
    public String Challenge = "";
    /**
     * public key generated by the plug.
     */
    public String PublicKey = "";
    /**
     * cookie generated by the plug.
     */
    public String Cookie = "";
    /**
     * private key generated to talk to the plug.
     */
    public String PrivateKey = "";
    /**
     * milliseconds to soap request timeout.
     */
    public Integer ConnectionTimeout = 3000;
}
